---


- name: Install WoeUSB dependencies
  apt:
    name:
      - git
      - p7zip-full
      - python3-pip
      - python3-wxgtk4.0
      - grub2-common
      - grub-pc-bin
  become: yes

- name: Install WoeUSB
  pip:
    name: WoeUSB-ng
  become: yes
